//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public decimal courseId { get; set; }
        public string courseShortName { get; set; }
        public string courseLongName { get; set; }
        public int credit { get; set; }
    }
}
